### ISSUE TITLE
create a flavor but failed on openstack

### ISSUE THREAD

**Issue by qct** [jclouds/legacy-jclouds#1581]
I try to create a flavor but failed, code is here:

```
Flavor flavor = novaApi.getFlavorApi("RegionOne").create(Flavor.builder()
        .name("qct-flavor-111")
        .vcpus(1)
        .ram(512)
        .disk(2)
        .id("10")
        .build());
```

exceptions here:

```
<< "{"badRequest": {"message": "Invalid input for field/attribute flavor. Value: {u'name': u'qct-flavor-111', u'links': [], u'ram': 512, u'vcpus': 1, u'disk': 2, u'id': u'10'}. Additional properties are not allowed (u'links' was unexpected)", "code": 400}}"
org.jclouds.http.HttpResponseException: command: POST http://192.168.9.192:8774/v2.1/695af97e057d4d0ebcf7b01799f7db0a/flavors HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [{"badRequest": {"message": "Invalid input for field/attribute flavor. Value: {u'name': u'qct-flavor-111', u'links': [], u'ram': 512, u'vcpus': 1, u'disk': 2, u'id': u'10'}. Additional properties are not allowed (u'links' was unexpected)", "code": 400}}]
         at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:78)
         at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
         at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136)
         at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105)
         at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
         at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
         at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
         at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
         at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
         at com.sun.proxy.$Proxy67.create(Unknown Source)
         at qct.test.JCloudsNova.creatFlavor(JCloudsNova.java:75)
         at qct.test.JCloudsNova.main(JCloudsNova.java:65)

```
maybe it's a bug, I can create flavor by directly post with params has no field links:
```
{"flavor":{"ram":512,"disk":2,"vcpus":1,"id":"10","name":"qct-flavor-111"
}}
```

jclouds transform fileds to this:

```
{"flavor":{"ram":512,"disk":2,"vcpus":1,"id":"10","name":"qct-flavor-111","links":[]}}
```

fileds links are not allowed.

**Comment by demobox** [comment]
@qct The `legacy-jclouds` repos are no longer used. Could you post your question to the [jclouds-user mailing list](http://jclouds.apache.org/community/)?

Thanks!
